# Generated by Django 4.2.7 on 2024-12-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='📚', max_length=10),
        ),
    ]
