# Generated by Django 4.2.7 on 2024-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['topic', 'id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['course', 'order']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='initial_code',
            new_name='solution_code',
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preview_topics',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='completed_exercises',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('coming-soon', 'Coming Soon')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=120, help_text='Total duration in minutes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='completed_topics',
            field=models.ManyToManyField(to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed')], default='enrolled', max_length=20),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='order',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated_at',
        ),
    ]
